[database]
dsn="mysql://root:123456@tcp(localhost:3306)/yt_judgery_prod?parseTime=True"

[secret]
# key: 32位
db_secret_key="b44982c8d69333e976e13cbb3ba127fb"

[logger]
env="prod"
level="debug"
output="log.txt"
