[database]
dsn="mysql://root:123456@tcp(localhost:3306)/yt_judgery_prod?parseTime=True"

[secret]
dec_secret_key="xxxxxxx"   #解密秘钥key: 32位
enc_secret_key="yyyyyyy"   #加密秘钥key: 32位

[logger]
env="prod"
level="debug"
output="log.txt"
